/**
 * @generated
 */
module.exports = {
  "dev-contributing": {
    "id": "dev-contributing",
    "title": "Contribution guidelines for Terra Core",
    "source": "contribute-contributing.md",
    "permalink": "docs/dev-contributing.html",
    "localized_id": "dev-contributing",
    "language": "en",
    "sidebar": "docs",
    "category": "Contribute",
    "subcategory": null,
    "order": 44,
    "next_id": "dev-help-translate",
    "next": "dev-help-translate",
    "previous_id": "dev-spec-market",
    "previous": "dev-spec-market",
    "previous_title": "Market",
    "next_title": "Help to translate"
  },
  "dev-help-translate": {
    "id": "dev-help-translate",
    "title": "Help to translate",
    "source": "contribute-help-translate.md",
    "permalink": "docs/dev-help-translate.html",
    "localized_id": "dev-help-translate",
    "language": "en",
    "sidebar": "docs",
    "category": "Contribute",
    "subcategory": null,
    "order": 45,
    "previous_id": "dev-contributing",
    "previous": "dev-contributing",
    "previous_title": "Contribution guidelines for Terra Core"
  },
  "dev-client-libraries": {
    "id": "dev-client-libraries",
    "title": "Client Libraries",
    "source": "dev-client-libraries.md",
    "permalink": "docs/dev-client-libraries.html",
    "localized_id": "dev-client-libraries",
    "language": "en",
    "sidebar": "docs",
    "category": "Developer Guide",
    "subcategory": null,
    "order": 33,
    "next_id": "dev-codebase",
    "next": "dev-codebase",
    "previous_id": "dev-getting-started",
    "previous": "dev-getting-started",
    "previous_title": "Getting Started",
    "next_title": "Codebase"
  },
  "dev-codebase": {
    "id": "dev-codebase",
    "title": "Codebase",
    "source": "dev-codebase.md",
    "permalink": "docs/dev-codebase.html",
    "localized_id": "dev-codebase",
    "language": "en",
    "sidebar": "docs",
    "category": "Developer Guide",
    "subcategory": null,
    "order": 34,
    "next_id": "dev-spec-distribution",
    "next": "dev-spec-distribution",
    "previous_id": "dev-client-libraries",
    "previous": "dev-client-libraries",
    "previous_title": "Client Libraries",
    "next_title": "Distribution"
  },
  "dev-getting-started": {
    "id": "dev-getting-started",
    "title": "Getting Started",
    "source": "dev-getting-started.md",
    "permalink": "docs/dev-getting-started.html",
    "localized_id": "dev-getting-started",
    "language": "en",
    "sidebar": "docs",
    "category": "Developer Guide",
    "subcategory": null,
    "order": 32,
    "next_id": "dev-client-libraries",
    "next": "dev-client-libraries",
    "previous_id": "validator-faq",
    "previous": "validator-faq",
    "previous_title": "Validator FAQ",
    "next_title": "Client Libraries"
  },
  "dev-spec-auth": {
    "id": "dev-spec-auth",
    "title": "Auth",
    "source": "dev-spec-auth.md",
    "permalink": "docs/dev-spec-auth.html",
    "localized_id": "dev-spec-auth",
    "language": "en",
    "sidebar": "docs",
    "category": "Developer Guide",
    "subcategory": "CORE MODULES",
    "order": 37,
    "next_id": "dev-spec-bank",
    "next": "dev-spec-bank",
    "previous_id": "dev-spec-staking",
    "previous": "dev-spec-staking",
    "previous_title": "Staking",
    "next_title": "Bank"
  },
  "dev-spec-bank": {
    "id": "dev-spec-bank",
    "title": "Bank",
    "source": "dev-spec-bank.md",
    "permalink": "docs/dev-spec-bank.html",
    "localized_id": "dev-spec-bank",
    "language": "en",
    "sidebar": "docs",
    "category": "Developer Guide",
    "subcategory": "CORE MODULES",
    "order": 38,
    "next_id": "dev-spec-supply",
    "next": "dev-spec-supply",
    "previous_id": "dev-spec-auth",
    "previous": "dev-spec-auth",
    "previous_title": "Auth",
    "next_title": "Supply"
  },
  "dev-spec-distribution": {
    "id": "dev-spec-distribution",
    "title": "Distribution",
    "source": "dev-spec-distribution.md",
    "permalink": "docs/dev-spec-distribution.html",
    "localized_id": "dev-spec-distribution",
    "language": "en",
    "sidebar": "docs",
    "category": "Developer Guide",
    "subcategory": "CORE MODULES",
    "order": 35,
    "next_id": "dev-spec-staking",
    "next": "dev-spec-staking",
    "previous_id": "dev-codebase",
    "previous": "dev-codebase",
    "previous_title": "Codebase",
    "next_title": "Staking"
  },
  "dev-spec-governance": {
    "id": "dev-spec-governance",
    "title": "Governance",
    "source": "dev-spec-governance.md",
    "permalink": "docs/dev-spec-governance.html",
    "localized_id": "dev-spec-governance",
    "language": "en",
    "sidebar": "docs",
    "category": "Developer Guide",
    "subcategory": "CORE MODULES",
    "order": 42,
    "next_id": "dev-spec-market",
    "next": "dev-spec-market",
    "previous_id": "dev-spec-treasury",
    "previous": "dev-spec-treasury",
    "previous_title": "Treasury",
    "next_title": "Market"
  },
  "dev-spec-market": {
    "id": "dev-spec-market",
    "title": "Market",
    "source": "dev-spec-market.md",
    "permalink": "docs/dev-spec-market.html",
    "localized_id": "dev-spec-market",
    "language": "en",
    "sidebar": "docs",
    "category": "Developer Guide",
    "subcategory": "CORE MODULES",
    "order": 43,
    "next_id": "dev-contributing",
    "next": "dev-contributing",
    "previous_id": "dev-spec-governance",
    "previous": "dev-spec-governance",
    "previous_title": "Governance",
    "next_title": "Contribution guidelines for Terra Core"
  },
  "dev-spec-oracle": {
    "id": "dev-spec-oracle",
    "title": "Oracle",
    "source": "dev-spec-oracle.md",
    "permalink": "docs/dev-spec-oracle.html",
    "localized_id": "dev-spec-oracle",
    "language": "en",
    "sidebar": "docs",
    "category": "Developer Guide",
    "subcategory": "CORE MODULES",
    "order": 40,
    "next_id": "dev-spec-treasury",
    "next": "dev-spec-treasury",
    "previous_id": "dev-spec-supply",
    "previous": "dev-spec-supply",
    "previous_title": "Supply",
    "next_title": "Treasury"
  },
  "dev-spec-staking": {
    "id": "dev-spec-staking",
    "title": "Staking",
    "source": "dev-spec-staking.md",
    "permalink": "docs/dev-spec-staking.html",
    "localized_id": "dev-spec-staking",
    "language": "en",
    "sidebar": "docs",
    "category": "Developer Guide",
    "subcategory": "CORE MODULES",
    "order": 36,
    "next_id": "dev-spec-auth",
    "next": "dev-spec-auth",
    "previous_id": "dev-spec-distribution",
    "previous": "dev-spec-distribution",
    "previous_title": "Distribution",
    "next_title": "Auth"
  },
  "dev-spec-supply": {
    "id": "dev-spec-supply",
    "title": "Supply",
    "source": "dev-spec-supply.md",
    "permalink": "docs/dev-spec-supply.html",
    "localized_id": "dev-spec-supply",
    "language": "en",
    "sidebar": "docs",
    "category": "Developer Guide",
    "subcategory": "CORE MODULES",
    "order": 39,
    "next_id": "dev-spec-oracle",
    "next": "dev-spec-oracle",
    "previous_id": "dev-spec-bank",
    "previous": "dev-spec-bank",
    "previous_title": "Bank",
    "next_title": "Oracle"
  },
  "dev-spec-treasury": {
    "id": "dev-spec-treasury",
    "title": "Treasury",
    "source": "dev-spec-treasury.md",
    "permalink": "docs/dev-spec-treasury.html",
    "localized_id": "dev-spec-treasury",
    "language": "en",
    "sidebar": "docs",
    "category": "Developer Guide",
    "subcategory": "CORE MODULES",
    "order": 41,
    "next_id": "dev-spec-governance",
    "next": "dev-spec-governance",
    "previous_id": "dev-spec-oracle",
    "previous": "dev-spec-oracle",
    "previous_title": "Oracle",
    "next_title": "Governance"
  },
  "dev-deploy-testnet": {
    "id": "dev-deploy-testnet",
    "title": "Deploy a testnet",
    "source": "node-deploy-testnet.md",
    "permalink": "docs/dev-deploy-testnet.html",
    "localized_id": "dev-deploy-testnet",
    "language": "en",
    "sidebar": "docs",
    "category": "Node Software",
    "subcategory": "GUIDES",
    "order": 27,
    "next_id": "validator-intro",
    "next": "validator-intro",
    "previous_id": "dev-join-network",
    "previous": "dev-join-network",
    "previous_title": "Join a network",
    "next_title": "Validator Guide"
  },
  "dev-installation": {
    "id": "dev-installation",
    "title": "Installation",
    "source": "node-installation.md",
    "permalink": "docs/dev-installation.html",
    "localized_id": "dev-installation",
    "language": "en",
    "sidebar": "docs",
    "category": "Node Software",
    "subcategory": null,
    "order": 20,
    "next_id": "dev-users",
    "next": "dev-users",
    "previous_id": "dev-comparison",
    "previous": "dev-comparison",
    "previous_title": "Terra vs. Other Stablecoins",
    "next_title": "User Guide"
  },
  "dev-join-network": {
    "id": "dev-join-network",
    "title": "Join a network",
    "source": "node-join-network.md",
    "permalink": "docs/dev-join-network.html",
    "localized_id": "dev-join-network",
    "language": "en",
    "sidebar": "docs",
    "category": "Node Software",
    "subcategory": "GUIDES",
    "order": 26,
    "next_id": "dev-deploy-testnet",
    "next": "dev-deploy-testnet",
    "previous_id": "dev-production",
    "previous": "dev-production",
    "previous_title": "Run a node for production",
    "next_title": "Deploy a testnet"
  },
  "dev-ledger-nano-support": {
    "id": "dev-ledger-nano-support",
    "title": "Ledger Nano S Support for Terra",
    "sidebar_label": "Ledger Nano Support",
    "source": "node-ledger-nano-support.md",
    "permalink": "docs/dev-ledger-nano-support.html",
    "localized_id": "dev-ledger-nano-support",
    "language": "en",
    "sidebar": "docs",
    "category": "Node Software",
    "subcategory": "GUIDES",
    "order": 24,
    "next_id": "dev-production",
    "next": "dev-production",
    "previous_id": "dev-terracli",
    "previous": "dev-terracli",
    "previous_title": "terracli Reference Guide",
    "next_title": "Run a node for production"
  },
  "dev-light-client": {
    "id": "dev-light-client",
    "title": "Light Client Daemon (LCD REST Server)",
    "sidebar_label": "Light Client Daemon",
    "source": "node-light-client.md",
    "permalink": "docs/dev-light-client.html",
    "localized_id": "dev-light-client",
    "language": "en",
    "sidebar": "docs",
    "category": "Node Software",
    "subcategory": null,
    "order": 22,
    "next_id": "dev-terracli",
    "next": "dev-terracli",
    "previous_id": "dev-users",
    "previous": "dev-users",
    "previous_title": "User Guide",
    "next_title": "terracli Reference Guide"
  },
  "dev-production": {
    "id": "dev-production",
    "title": "Run a node for production",
    "source": "node-production.md",
    "permalink": "docs/dev-production.html",
    "localized_id": "dev-production",
    "language": "en",
    "sidebar": "docs",
    "category": "Node Software",
    "subcategory": "GUIDES",
    "order": 25,
    "next_id": "dev-join-network",
    "next": "dev-join-network",
    "previous_id": "dev-ledger-nano-support",
    "previous": "dev-ledger-nano-support",
    "previous_title": "Ledger Nano S Support for Terra",
    "next_title": "Join a network"
  },
  "dev-terracli": {
    "id": "dev-terracli",
    "title": "terracli Reference Guide",
    "source": "node-terracli.md",
    "permalink": "docs/dev-terracli.html",
    "localized_id": "dev-terracli",
    "language": "en",
    "sidebar": "docs",
    "category": "Node Software",
    "subcategory": "GUIDES",
    "order": 23,
    "next_id": "dev-ledger-nano-support",
    "next": "dev-ledger-nano-support",
    "previous_id": "dev-light-client",
    "previous": "dev-light-client",
    "previous_title": "Light Client Daemon (LCD REST Server)",
    "next_title": "Ledger Nano S Support for Terra"
  },
  "dev-users": {
    "id": "dev-users",
    "title": "User Guide",
    "source": "node-users.md",
    "permalink": "docs/dev-users.html",
    "localized_id": "dev-users",
    "language": "en",
    "sidebar": "docs",
    "category": "Node Software",
    "subcategory": null,
    "order": 21,
    "next_id": "dev-light-client",
    "next": "dev-light-client",
    "previous_id": "dev-installation",
    "previous": "dev-installation",
    "previous_title": "Installation",
    "next_title": "Light Client Daemon (LCD REST Server)"
  },
  "dev-faq": {
    "id": "dev-faq",
    "title": "Terra FAQ",
    "source": "overview-faq.md",
    "permalink": "docs/dev-faq.html",
    "localized_id": "dev-faq",
    "language": "en",
    "sidebar": "docs",
    "category": "Overview",
    "subcategory": null,
    "order": 2,
    "next_id": "dev-what-is-terra",
    "next": "dev-what-is-terra",
    "previous_id": "dev-intro",
    "previous": "dev-intro",
    "previous_title": "Terra Documentation",
    "next_title": "What is Terra?"
  },
  "dev-intro": {
    "id": "dev-intro",
    "title": "Terra Documentation",
    "sidebar_label": "Introduction",
    "source": "overview-intro.md",
    "permalink": "docs/dev-intro.html",
    "localized_id": "dev-intro",
    "language": "en",
    "sidebar": "docs",
    "category": "Overview",
    "subcategory": null,
    "order": 1,
    "next_id": "dev-faq",
    "next": "dev-faq",
    "next_title": "Terra FAQ"
  },
  "dev-accounts-wallets": {
    "id": "dev-accounts-wallets",
    "title": "Accounts & Wallets",
    "source": "proto-accounts-wallets.md",
    "permalink": "docs/dev-accounts-wallets.html",
    "localized_id": "dev-accounts-wallets",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "BASICS",
    "order": 5,
    "next_id": "dev-transaction",
    "next": "dev-transaction",
    "previous_id": "dev-how-terra-works",
    "previous": "dev-how-terra-works",
    "previous_title": "How Terra Works",
    "next_title": "Transactions"
  },
  "dev-comparison": {
    "id": "dev-comparison",
    "title": "Terra vs. Other Stablecoins",
    "sidebar_label": "Other Stablecoins",
    "source": "proto-comparison.md",
    "permalink": "docs/dev-comparison.html",
    "localized_id": "dev-comparison",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "TERRA VS. ...",
    "order": 19,
    "next_id": "dev-installation",
    "next": "dev-installation",
    "previous_id": "dev-dapp-platform",
    "previous": "dev-dapp-platform",
    "previous_title": "Powering the Innovation of Money",
    "next_title": "Installation"
  },
  "dev-dapp-platform": {
    "id": "dev-dapp-platform",
    "title": "Powering the Innovation of Money",
    "source": "proto-dapp-platform.md",
    "permalink": "docs/dev-dapp-platform.html",
    "localized_id": "dev-dapp-platform",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "ADOPTION",
    "order": 18,
    "next_id": "dev-comparison",
    "next": "dev-comparison",
    "previous_id": "dev-governance",
    "previous": "dev-governance",
    "previous_title": "Governance",
    "next_title": "Terra vs. Other Stablecoins"
  },
  "dev-fiscal-policy": {
    "id": "dev-fiscal-policy",
    "title": "Fiscal Policy",
    "source": "proto-fiscal-policy.md",
    "permalink": "docs/dev-fiscal-policy.html",
    "localized_id": "dev-fiscal-policy",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "ADOPTION",
    "order": 15,
    "next_id": "dev-treasury",
    "next": "dev-treasury",
    "previous_id": "dev-miner-incentives",
    "previous": "dev-miner-incentives",
    "previous_title": "Miner Incentives",
    "next_title": "Treasury"
  },
  "dev-governance": {
    "id": "dev-governance",
    "title": "Governance",
    "source": "proto-governance.md",
    "permalink": "docs/dev-governance.html",
    "localized_id": "dev-governance",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "ADOPTION",
    "order": 17,
    "next_id": "dev-dapp-platform",
    "next": "dev-dapp-platform",
    "previous_id": "dev-treasury",
    "previous": "dev-treasury",
    "previous_title": "Treasury",
    "next_title": "Powering the Innovation of Money"
  },
  "dev-how-terra-works": {
    "id": "dev-how-terra-works",
    "title": "How Terra Works",
    "source": "proto-how-terra-works.md",
    "permalink": "docs/dev-how-terra-works.html",
    "localized_id": "dev-how-terra-works",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": null,
    "order": 4,
    "next_id": "dev-accounts-wallets",
    "next": "dev-accounts-wallets",
    "previous_id": "dev-what-is-terra",
    "previous": "dev-what-is-terra",
    "previous_title": "What is Terra?",
    "next_title": "Accounts & Wallets"
  },
  "dev-luna-staking": {
    "id": "dev-luna-staking",
    "title": "Luna & Staking",
    "source": "proto-luna-staking.md",
    "permalink": "docs/dev-luna-staking.html",
    "localized_id": "dev-luna-staking",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "MINING & CONSENSUS",
    "order": 8,
    "next_id": "dev-validators",
    "next": "dev-validators",
    "previous_id": "dev-dpos",
    "previous": "dev-dpos",
    "previous_title": "Delegated Proof-of-Stake (DPoS)",
    "next_title": "Validators"
  },
  "dev-miner-incentives": {
    "id": "dev-miner-incentives",
    "title": "Miner Incentives",
    "source": "proto-miner-incentives.md",
    "permalink": "docs/dev-miner-incentives.html",
    "localized_id": "dev-miner-incentives",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "STABILITY",
    "order": 14,
    "next_id": "dev-fiscal-policy",
    "next": "dev-fiscal-policy",
    "previous_id": "dev-stabilization",
    "previous": "dev-stabilization",
    "previous_title": "Price Stabilization",
    "next_title": "Fiscal Policy"
  },
  "dev-monetary-policy": {
    "id": "dev-monetary-policy",
    "title": "Monetary Policy",
    "source": "proto-monetary-policy.md",
    "permalink": "docs/dev-monetary-policy.html",
    "localized_id": "dev-monetary-policy",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "STABILITY",
    "order": 11,
    "next_id": "dev-subcurrencies",
    "next": "dev-subcurrencies",
    "previous_id": "dev-price-oracle",
    "previous": "dev-price-oracle",
    "previous_title": "Price Oracle",
    "next_title": "Subcurrencies"
  },
  "dev-price-oracle": {
    "id": "dev-price-oracle",
    "title": "Price Oracle",
    "source": "proto-price-oracle.md",
    "permalink": "docs/dev-price-oracle.html",
    "localized_id": "dev-price-oracle",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "MINING & CONSENSUS",
    "order": 10,
    "next_id": "dev-monetary-policy",
    "next": "dev-monetary-policy",
    "previous_id": "dev-validators",
    "previous": "dev-validators",
    "previous_title": "Validators",
    "next_title": "Monetary Policy"
  },
  "dev-seigniorage": {
    "id": "dev-seigniorage",
    "title": "Seigniorage",
    "source": "proto-seigniorage.md",
    "permalink": "docs/dev-seigniorage.html",
    "localized_id": "dev-seigniorage",
    "language": "en"
  },
  "dev-stabilization": {
    "id": "dev-stabilization",
    "title": "Price Stabilization",
    "source": "proto-stabilization.md",
    "permalink": "docs/dev-stabilization.html",
    "localized_id": "dev-stabilization",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "STABILITY",
    "order": 13,
    "next_id": "dev-miner-incentives",
    "next": "dev-miner-incentives",
    "previous_id": "dev-subcurrencies",
    "previous": "dev-subcurrencies",
    "previous_title": "Subcurrencies",
    "next_title": "Miner Incentives"
  },
  "dev-subcurrencies": {
    "id": "dev-subcurrencies",
    "title": "Subcurrencies",
    "source": "proto-subcurrencies.md",
    "permalink": "docs/dev-subcurrencies.html",
    "localized_id": "dev-subcurrencies",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "STABILITY",
    "order": 12,
    "next_id": "dev-stabilization",
    "next": "dev-stabilization",
    "previous_id": "dev-monetary-policy",
    "previous": "dev-monetary-policy",
    "previous_title": "Monetary Policy",
    "next_title": "Price Stabilization"
  },
  "dev-dpos": {
    "id": "dev-dpos",
    "title": "Delegated Proof-of-Stake (DPoS)",
    "source": "proto-tendermint-bft.md",
    "permalink": "docs/dev-dpos.html",
    "localized_id": "dev-dpos",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "MINING & CONSENSUS",
    "order": 7,
    "next_id": "dev-luna-staking",
    "next": "dev-luna-staking",
    "previous_id": "dev-transaction",
    "previous": "dev-transaction",
    "previous_title": "Transactions",
    "next_title": "Luna & Staking"
  },
  "dev-transaction": {
    "id": "dev-transaction",
    "title": "Transactions",
    "source": "proto-transactions.md",
    "permalink": "docs/dev-transaction.html",
    "localized_id": "dev-transaction",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "BASICS",
    "order": 6,
    "next_id": "dev-dpos",
    "next": "dev-dpos",
    "previous_id": "dev-accounts-wallets",
    "previous": "dev-accounts-wallets",
    "previous_title": "Accounts & Wallets",
    "next_title": "Delegated Proof-of-Stake (DPoS)"
  },
  "dev-treasury": {
    "id": "dev-treasury",
    "title": "Treasury",
    "source": "proto-treasury.md",
    "permalink": "docs/dev-treasury.html",
    "localized_id": "dev-treasury",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "ADOPTION",
    "order": 16,
    "next_id": "dev-governance",
    "next": "dev-governance",
    "previous_id": "dev-fiscal-policy",
    "previous": "dev-fiscal-policy",
    "previous_title": "Fiscal Policy",
    "next_title": "Governance"
  },
  "dev-validators": {
    "id": "dev-validators",
    "title": "Validators",
    "source": "proto-validators.md",
    "permalink": "docs/dev-validators.html",
    "localized_id": "dev-validators",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "MINING & CONSENSUS",
    "order": 9,
    "next_id": "dev-price-oracle",
    "next": "dev-price-oracle",
    "previous_id": "dev-luna-staking",
    "previous": "dev-luna-staking",
    "previous_title": "Luna & Staking",
    "next_title": "Price Oracle"
  },
  "dev-what-is-terra": {
    "id": "dev-what-is-terra",
    "title": "What is Terra?",
    "source": "proto-what-is-terra.md",
    "permalink": "docs/dev-what-is-terra.html",
    "localized_id": "dev-what-is-terra",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": null,
    "order": 3,
    "next_id": "dev-how-terra-works",
    "next": "dev-how-terra-works",
    "previous_id": "dev-faq",
    "previous": "dev-faq",
    "previous_title": "Terra FAQ",
    "next_title": "How Terra Works"
  },
  "validator-faq": {
    "id": "validator-faq",
    "title": "Validator FAQ",
    "source": "validator-faq.md",
    "permalink": "docs/validator-faq.html",
    "localized_id": "validator-faq",
    "language": "en",
    "sidebar": "docs",
    "category": "Validator Guide",
    "subcategory": null,
    "order": 31,
    "next_id": "dev-getting-started",
    "next": "dev-getting-started",
    "previous_id": "validator-security",
    "previous": "validator-security",
    "previous_title": "Security",
    "next_title": "Getting Started"
  },
  "validator-getting-started": {
    "id": "validator-getting-started",
    "title": "Getting Started",
    "source": "validator-getting-started.md",
    "permalink": "docs/validator-getting-started.html",
    "localized_id": "validator-getting-started",
    "language": "en",
    "sidebar": "docs",
    "category": "Validator Guide",
    "subcategory": null,
    "order": 29,
    "next_id": "validator-security",
    "next": "validator-security",
    "previous_id": "validator-intro",
    "previous": "validator-intro",
    "previous_title": "Validator Guide",
    "next_title": "Security"
  },
  "validator-intro": {
    "id": "validator-intro",
    "title": "Validator Guide",
    "sidebar_label": "Introduction",
    "source": "validator-intro.md",
    "permalink": "docs/validator-intro.html",
    "localized_id": "validator-intro",
    "language": "en",
    "sidebar": "docs",
    "category": "Validator Guide",
    "subcategory": null,
    "order": 28,
    "next_id": "validator-getting-started",
    "next": "validator-getting-started",
    "previous_id": "dev-deploy-testnet",
    "previous": "dev-deploy-testnet",
    "previous_title": "Deploy a testnet",
    "next_title": "Getting Started"
  },
  "validator-security": {
    "id": "validator-security",
    "title": "Security",
    "source": "validator-security.md",
    "permalink": "docs/validator-security.html",
    "localized_id": "validator-security",
    "language": "en",
    "sidebar": "docs",
    "category": "Validator Guide",
    "subcategory": null,
    "order": 30,
    "next_id": "validator-faq",
    "next": "validator-faq",
    "previous_id": "validator-getting-started",
    "previous": "validator-getting-started",
    "previous_title": "Getting Started",
    "next_title": "Validator FAQ"
  }
};
