/**
 * @generated
 */
module.exports = {
  "columbus3": {
    "id": "columbus3",
    "title": "Columbus-3 Mainnet",
    "source": "columbus3.md",
    "permalink": "docs/columbus3.html",
    "localized_id": "columbus3",
    "language": "en",
    "sidebar": "docs",
    "category": "Overview",
    "subcategory": null,
    "order": 2,
    "next_id": "dev-how-terra-works",
    "next": "dev-how-terra-works",
    "previous_id": "index",
    "previous": "index",
    "previous_title": "Terra Documentation",
    "next_title": "How Terra Works"
  },
  "contribute-contributing": {
    "id": "contribute-contributing",
    "title": "Getting involved with Terra",
    "source": "contribute-contributing.md",
    "permalink": "docs/contribute-contributing.html",
    "localized_id": "contribute-contributing",
    "language": "en",
    "sidebar": "docs",
    "category": "Contribute",
    "subcategory": null,
    "order": 28,
    "previous_id": "validator-oracle",
    "previous": "validator-oracle",
    "previous_title": "Exchange Rate Oracle"
  },
  "dev-conventions": {
    "id": "dev-conventions",
    "title": "Conventions",
    "source": "dev-conventions.md",
    "permalink": "docs/dev-conventions.html",
    "localized_id": "dev-conventions",
    "language": "en"
  },
  "dev-devguide": {
    "id": "dev-devguide",
    "title": "Notes for Developers",
    "source": "dev-devguide.md",
    "permalink": "docs/dev-devguide.html",
    "localized_id": "dev-devguide",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": null,
    "order": 4,
    "next_id": "dev-spec-auth",
    "next": "dev-spec-auth",
    "previous_id": "dev-how-terra-works",
    "previous": "dev-how-terra-works",
    "previous_title": "How Terra Works",
    "next_title": "Auth"
  },
  "dev-how-terra-works": {
    "id": "dev-how-terra-works",
    "title": "How Terra Works",
    "source": "dev-how-terra-works.md",
    "permalink": "docs/dev-how-terra-works.html",
    "localized_id": "dev-how-terra-works",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": null,
    "order": 3,
    "next_id": "dev-devguide",
    "next": "dev-devguide",
    "previous_id": "columbus3",
    "previous": "columbus3",
    "previous_title": "Columbus-3 Mainnet",
    "next_title": "Notes for Developers"
  },
  "dev-spec-auth": {
    "id": "dev-spec-auth",
    "title": "Auth",
    "source": "dev-spec-auth.md",
    "permalink": "docs/dev-spec-auth.html",
    "localized_id": "dev-spec-auth",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "MODULE SPECS",
    "order": 5,
    "next_id": "dev-spec-bank",
    "next": "dev-spec-bank",
    "previous_id": "dev-devguide",
    "previous": "dev-devguide",
    "previous_title": "Notes for Developers",
    "next_title": "Bank"
  },
  "dev-spec-bank": {
    "id": "dev-spec-bank",
    "title": "Bank",
    "source": "dev-spec-bank.md",
    "permalink": "docs/dev-spec-bank.html",
    "localized_id": "dev-spec-bank",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "MODULE SPECS",
    "order": 6,
    "next_id": "dev-spec-supply",
    "next": "dev-spec-supply",
    "previous_id": "dev-spec-auth",
    "previous": "dev-spec-auth",
    "previous_title": "Auth",
    "next_title": "Supply"
  },
  "dev-spec-distribution": {
    "id": "dev-spec-distribution",
    "title": "Distribution",
    "source": "dev-spec-distribution.md",
    "permalink": "docs/dev-spec-distribution.html",
    "localized_id": "dev-spec-distribution",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "MODULE SPECS",
    "order": 8,
    "next_id": "dev-spec-staking",
    "next": "dev-spec-staking",
    "previous_id": "dev-spec-supply",
    "previous": "dev-spec-supply",
    "previous_title": "Supply",
    "next_title": "Staking"
  },
  "dev-spec-governance": {
    "id": "dev-spec-governance",
    "title": "Governance",
    "source": "dev-spec-governance.md",
    "permalink": "docs/dev-spec-governance.html",
    "localized_id": "dev-spec-governance",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "MODULE SPECS",
    "order": 14,
    "next_id": "node-installation",
    "next": "node-installation",
    "previous_id": "dev-spec-treasury",
    "previous": "dev-spec-treasury",
    "previous_title": "Treasury",
    "next_title": "Installation"
  },
  "dev-spec-market": {
    "id": "dev-spec-market",
    "title": "Market",
    "source": "dev-spec-market.md",
    "permalink": "docs/dev-spec-market.html",
    "localized_id": "dev-spec-market",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "MODULE SPECS",
    "order": 12,
    "next_id": "dev-spec-treasury",
    "next": "dev-spec-treasury",
    "previous_id": "dev-spec-oracle",
    "previous": "dev-spec-oracle",
    "previous_title": "Oracle",
    "next_title": "Treasury"
  },
  "dev-spec-oracle": {
    "id": "dev-spec-oracle",
    "title": "Oracle",
    "source": "dev-spec-oracle.md",
    "permalink": "docs/dev-spec-oracle.html",
    "localized_id": "dev-spec-oracle",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "MODULE SPECS",
    "order": 11,
    "next_id": "dev-spec-market",
    "next": "dev-spec-market",
    "previous_id": "dev-spec-slashing",
    "previous": "dev-spec-slashing",
    "previous_title": "Slashing",
    "next_title": "Market"
  },
  "dev-spec-slashing": {
    "id": "dev-spec-slashing",
    "title": "Slashing",
    "source": "dev-spec-slashing.md",
    "permalink": "docs/dev-spec-slashing.html",
    "localized_id": "dev-spec-slashing",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "MODULE SPECS",
    "order": 10,
    "next_id": "dev-spec-oracle",
    "next": "dev-spec-oracle",
    "previous_id": "dev-spec-staking",
    "previous": "dev-spec-staking",
    "previous_title": "Staking",
    "next_title": "Oracle"
  },
  "dev-spec-staking": {
    "id": "dev-spec-staking",
    "title": "Staking",
    "source": "dev-spec-staking.md",
    "permalink": "docs/dev-spec-staking.html",
    "localized_id": "dev-spec-staking",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "MODULE SPECS",
    "order": 9,
    "next_id": "dev-spec-slashing",
    "next": "dev-spec-slashing",
    "previous_id": "dev-spec-distribution",
    "previous": "dev-spec-distribution",
    "previous_title": "Distribution",
    "next_title": "Slashing"
  },
  "dev-spec-supply": {
    "id": "dev-spec-supply",
    "title": "Supply",
    "source": "dev-spec-supply.md",
    "permalink": "docs/dev-spec-supply.html",
    "localized_id": "dev-spec-supply",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "MODULE SPECS",
    "order": 7,
    "next_id": "dev-spec-distribution",
    "next": "dev-spec-distribution",
    "previous_id": "dev-spec-bank",
    "previous": "dev-spec-bank",
    "previous_title": "Bank",
    "next_title": "Distribution"
  },
  "dev-spec-treasury": {
    "id": "dev-spec-treasury",
    "title": "Treasury",
    "source": "dev-spec-treasury.md",
    "permalink": "docs/dev-spec-treasury.html",
    "localized_id": "dev-spec-treasury",
    "language": "en",
    "sidebar": "docs",
    "category": "Terra Protocol",
    "subcategory": "MODULE SPECS",
    "order": 13,
    "next_id": "dev-spec-governance",
    "next": "dev-spec-governance",
    "previous_id": "dev-spec-market",
    "previous": "dev-spec-market",
    "previous_title": "Market",
    "next_title": "Governance"
  },
  "index": {
    "id": "index",
    "title": "Terra Documentation",
    "sidebar_label": "Introduction",
    "source": "intro.md",
    "permalink": "docs/index.html",
    "localized_id": "index",
    "language": "en",
    "sidebar": "docs",
    "category": "Overview",
    "subcategory": null,
    "order": 1,
    "next_id": "columbus3",
    "next": "columbus3",
    "next_title": "Columbus-3 Mainnet"
  },
  "node-deploy-testnet": {
    "id": "node-deploy-testnet",
    "title": "Deploy a Testnet",
    "source": "node-deploy-testnet.md",
    "permalink": "docs/node-deploy-testnet.html",
    "localized_id": "node-deploy-testnet",
    "language": "en",
    "sidebar": "docs",
    "category": "User Manual",
    "subcategory": "NODE SOFTWARE",
    "order": 22,
    "next_id": "validator-intro",
    "next": "validator-intro",
    "previous_id": "node-join-network",
    "previous": "node-join-network",
    "previous_title": "Join a Network",
    "next_title": "Validator Handbook"
  },
  "node-governance": {
    "id": "node-governance",
    "title": "Participate in Governance",
    "source": "node-governance.md",
    "permalink": "docs/node-governance.html",
    "localized_id": "node-governance",
    "language": "en"
  },
  "node-installation": {
    "id": "node-installation",
    "title": "Installation",
    "source": "node-installation.md",
    "permalink": "docs/node-installation.html",
    "localized_id": "node-installation",
    "language": "en",
    "sidebar": "docs",
    "category": "User Manual",
    "subcategory": "NODE SOFTWARE",
    "order": 15,
    "next_id": "node-users",
    "next": "node-users",
    "previous_id": "dev-spec-governance",
    "previous": "dev-spec-governance",
    "previous_title": "Governance",
    "next_title": "User Guide"
  },
  "node-join-network": {
    "id": "node-join-network",
    "title": "Join a Network",
    "source": "node-join-network.md",
    "permalink": "docs/node-join-network.html",
    "localized_id": "node-join-network",
    "language": "en",
    "sidebar": "docs",
    "category": "User Manual",
    "subcategory": "NODE SOFTWARE",
    "order": 21,
    "next_id": "node-deploy-testnet",
    "next": "node-deploy-testnet",
    "previous_id": "node-production",
    "previous": "node-production",
    "previous_title": "Production Settings",
    "next_title": "Deploy a Testnet"
  },
  "node-ledger-nano-support": {
    "id": "node-ledger-nano-support",
    "title": "Ledger Nano S Support for Terra",
    "sidebar_label": "Ledger Nano Support",
    "source": "node-ledger-nano-support.md",
    "permalink": "docs/node-ledger-nano-support.html",
    "localized_id": "node-ledger-nano-support",
    "language": "en",
    "sidebar": "docs",
    "category": "User Manual",
    "subcategory": "NODE SOFTWARE",
    "order": 19,
    "next_id": "node-production",
    "next": "node-production",
    "previous_id": "node-terracli",
    "previous": "node-terracli",
    "previous_title": "terracli Reference",
    "next_title": "Production Settings"
  },
  "node-light-client": {
    "id": "node-light-client",
    "title": "Light Client Daemon (LCD REST Server)",
    "sidebar_label": "Light Client Daemon",
    "source": "node-light-client.md",
    "permalink": "docs/node-light-client.html",
    "localized_id": "node-light-client",
    "language": "en",
    "sidebar": "docs",
    "category": "User Manual",
    "subcategory": "NODE SOFTWARE",
    "order": 17,
    "next_id": "node-terracli",
    "next": "node-terracli",
    "previous_id": "node-users",
    "previous": "node-users",
    "previous_title": "User Guide",
    "next_title": "terracli Reference"
  },
  "node-production": {
    "id": "node-production",
    "title": "Production Settings",
    "source": "node-production.md",
    "permalink": "docs/node-production.html",
    "localized_id": "node-production",
    "language": "en",
    "sidebar": "docs",
    "category": "User Manual",
    "subcategory": "NODE SOFTWARE",
    "order": 20,
    "next_id": "node-join-network",
    "next": "node-join-network",
    "previous_id": "node-ledger-nano-support",
    "previous": "node-ledger-nano-support",
    "previous_title": "Ledger Nano S Support for Terra",
    "next_title": "Join a Network"
  },
  "node-terracli": {
    "id": "node-terracli",
    "title": "terracli Reference",
    "source": "node-terracli.md",
    "permalink": "docs/node-terracli.html",
    "localized_id": "node-terracli",
    "language": "en",
    "sidebar": "docs",
    "category": "User Manual",
    "subcategory": "NODE SOFTWARE",
    "order": 18,
    "next_id": "node-ledger-nano-support",
    "next": "node-ledger-nano-support",
    "previous_id": "node-light-client",
    "previous": "node-light-client",
    "previous_title": "Light Client Daemon (LCD REST Server)",
    "next_title": "Ledger Nano S Support for Terra"
  },
  "node-users": {
    "id": "node-users",
    "title": "User Guide",
    "source": "node-users.md",
    "permalink": "docs/node-users.html",
    "localized_id": "node-users",
    "language": "en",
    "sidebar": "docs",
    "category": "User Manual",
    "subcategory": "NODE SOFTWARE",
    "order": 16,
    "next_id": "node-light-client",
    "next": "node-light-client",
    "previous_id": "node-installation",
    "previous": "node-installation",
    "previous_title": "Installation",
    "next_title": "Light Client Daemon (LCD REST Server)"
  },
  "validator-faq": {
    "id": "validator-faq",
    "title": "Validator FAQ",
    "source": "validator-faq.md",
    "permalink": "docs/validator-faq.html",
    "localized_id": "validator-faq",
    "language": "en",
    "sidebar": "docs",
    "category": "Validator Handbook",
    "subcategory": null,
    "order": 24,
    "next_id": "validator-getting-started",
    "next": "validator-getting-started",
    "previous_id": "validator-intro",
    "previous": "validator-intro",
    "previous_title": "Validator Handbook",
    "next_title": "Getting Started"
  },
  "validator-getting-started": {
    "id": "validator-getting-started",
    "title": "Getting Started",
    "source": "validator-getting-started.md",
    "permalink": "docs/validator-getting-started.html",
    "localized_id": "validator-getting-started",
    "language": "en",
    "sidebar": "docs",
    "category": "Validator Handbook",
    "subcategory": "GUIDES",
    "order": 25,
    "next_id": "validator-security",
    "next": "validator-security",
    "previous_id": "validator-faq",
    "previous": "validator-faq",
    "previous_title": "Validator FAQ",
    "next_title": "Security Best Practices"
  },
  "validator-intro": {
    "id": "validator-intro",
    "title": "Validator Handbook",
    "sidebar_label": "Introduction",
    "source": "validator-intro.md",
    "permalink": "docs/validator-intro.html",
    "localized_id": "validator-intro",
    "language": "en",
    "sidebar": "docs",
    "category": "Validator Handbook",
    "subcategory": null,
    "order": 23,
    "next_id": "validator-faq",
    "next": "validator-faq",
    "previous_id": "node-deploy-testnet",
    "previous": "node-deploy-testnet",
    "previous_title": "Deploy a Testnet",
    "next_title": "Validator FAQ"
  },
  "validator-oracle": {
    "id": "validator-oracle",
    "title": "Exchange Rate Oracle",
    "source": "validator-oracle.md",
    "permalink": "docs/validator-oracle.html",
    "localized_id": "validator-oracle",
    "language": "en",
    "sidebar": "docs",
    "category": "Validator Handbook",
    "subcategory": "GUIDES",
    "order": 27,
    "next_id": "contribute-contributing",
    "next": "contribute-contributing",
    "previous_id": "validator-security",
    "previous": "validator-security",
    "previous_title": "Security Best Practices",
    "next_title": "Getting involved with Terra"
  },
  "validator-security": {
    "id": "validator-security",
    "title": "Security Best Practices",
    "source": "validator-security.md",
    "permalink": "docs/validator-security.html",
    "localized_id": "validator-security",
    "language": "en",
    "sidebar": "docs",
    "category": "Validator Handbook",
    "subcategory": "GUIDES",
    "order": 26,
    "next_id": "validator-oracle",
    "next": "validator-oracle",
    "previous_id": "validator-getting-started",
    "previous": "validator-getting-started",
    "previous_title": "Getting Started",
    "next_title": "Exchange Rate Oracle"
  },
  "validator-troubleshooting": {
    "id": "validator-troubleshooting",
    "title": "Validator Troubleshooting",
    "sidebar_label": "Troubleshooting",
    "source": "validator-troubleshooting.md",
    "permalink": "docs/validator-troubleshooting.html",
    "localized_id": "validator-troubleshooting",
    "language": "en"
  }
};
